DevFolio/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import *

urlpatterns = [
    # path('', handleIndexPage, name='IndexView'),
    path('', IndexPageView.as_view(), name='IndexView'),
    path('article/<int:pk>/', blogSingleView, name='BlogSingleView'),
    path('article/archive_in_month/<int:month>/', handle_archive_month, name='ArchiveMonth'),
]

blog/models.py
from PIL import Image
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class AboutMe(models.Model):
    userprofile = models.OneToOneField('UserProfile', on_delete=models.CASCADE)
    phoneNumber = models.CharField(max_length=11)
    description = RichTextField(blank=True)

    def __str__(self):
        return f'{self.userprofile.user.first_name}'

    class Meta:
        verbose_name_plural = 'AboutMe'


def get_about_me():
    if AboutMe.objects.filter(userprofile__user__first_name__exact='پوریا').exists():
        return AboutMe.objects.get(userprofile__user__first_name__exact='پوریا')
    else:
        return None


class MySkills(models.Model):
    name = models.CharField(max_length=50)
    percentages = models.IntegerField()

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name_plural = 'MySkills'


def get_my_skills():
    return MySkills.objects.all()


class Services(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    icon = models.CharField(max_length=200)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name_plural = 'Services'


def get_my_services():
    return Services.objects.all()


class Reputations(models.Model):
    name = models.CharField(max_length=50)
    number = models.IntegerField()
    icon = models.CharField(max_length=200)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name_plural = 'Reputations'


def get_my_reputations():
    return Reputations.objects.all()


class Category(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % self.title

    class Meta:
        verbose_name_plural = 'Categories'


class Projects(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    done_at = models.DateTimeField(auto_now_add=True)
    img = models.ImageField(upload_to='images/', default='')
    url = models.URLField(null=True, blank=True)

    def __str__(self):
        return '%s' % self.title

    class Meta:
        verbose_name_plural = 'Projects'


def get_my_projects():
    return Projects.objects.all()


class Testimonials(models.Model):
    userprofile = models.OneToOneField('UserProfile', on_delete=models.CASCADE)
    description = models.TextField()

    def __str__(self):
        return self.userprofile.user.first_name

    class Meta:
        verbose_name_plural = 'Testimonials'


def get_my_testimonials():
    return Testimonials.objects.all()


class UserProfile(models.Model):
    avatar = models.ImageField(upload_to='images/', default='')
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.avatar.path)
        if img.height > 400 or img.width > 400:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.avatar.path)

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

    class Meta:
        verbose_name_plural = 'UserProfiles'


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    cover = models.ImageField(upload_to='images/', default='')
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    created_at = models.DateTimeField(timezone.now())
    updated_at = models.DateTimeField(auto_now=True)
    content = RichTextUploadingField(blank=True)
    short_description = RichTextField()
    time_to_read = models.CharField(max_length=30)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Articles'


def get_all_articles():
    return Article.objects.all().order_by('-created_at')


def get_specific_articles(args):
    return Article.objects.filter(created_at__month=args)


class CommentUs(models.Model):
    STATUS_CHOICES = (
        ('male', 'مرد'),
        ('female', 'زن'),
    )
    name = models.CharField(max_length=50)
    email = models.EmailField()
    content = RichTextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    gender = models.CharField(max_length=6, choices=STATUS_CHOICES)

    def __str__(self):
        return 'Comment by ' + self.name

    class Meta:
        verbose_name_plural = 'Comments'
        ordering = ('-created_at',)


def get_specific_comments(args):
    return CommentUs.objects.filter(article__title=args)


# class Reply(models.Model):
#     STATUS_CHOICES = (
#         ('male', 'male'),
#         ('female', 'female'),
#     )
#     commentUs = models.ForeignKey(CommentUs, on_delete=models.CASCADE)
#     name = models.CharField(max_length=50)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#     content = models.TextField()
#     gender = models.CharField(max_length=6,default='male')
#
#     class Meta:
#         verbose_name_plural = 'Replies'
#         ordering = ('-created_at',)
#
#     def __str__(self):
#         return 'Replied by ' + self.name


class ContactUs(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=50, blank=True)
    content = RichTextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'ContactUs'

blog/forms.py
from django import forms
from .models import ContactUs, CommentUs


class ContactUsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'form-control',
             'placeholder': 'نام شما',
             'data-rule': 'minlen:4',
             'data-msg': 'لطفا بیشتر از 4 کاراکتر وارد کنید'}
        )
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control',
             'placeholder': 'ایمیل شما',
             'data-rule': 'email',
             'data-msg': 'لطفا ایمیل معتبر وارد کنید'}
        )
        self.fields['subject'].widget.attrs.update(
            {'class': 'form-control',
             'placeholder': 'موضوع کنید',
             'data-rule': 'minlen:4',
             'data-msg': 'لطفا بیشتر از 8 کاراکتر وارد کنید'}
        )
        self.fields['content'].widget.attrs.update(
            {'class': 'form-control',
             'placeholder': 'پیام',
             'data-rule': 'required',
             'rows': '5',
             'data-msg': 'پیام خود را برا ی ما بنویسید'}
        )

    class Meta:
        model = ContactUs
        fields = '__all__'
        widgets = {
            'email': forms.EmailInput(),
            # 'content': forms.TextInput(),
        }


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'form-control input-mf',
             'placeholder': 'نام *',
             'required': 'required'
             }
        )
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control input-mf',
             'placeholder': 'ایمیل *',
             'required': 'required'}
        )
        self.fields['content'].widget.attrs.update(
            {'class': 'form-control input-mf',
             'placeholder': 'نظر *',
             'required': 'required',
             'type': 'textarea'}
        )

    class Meta:
        model = CommentUs
        fields = ['name', 'email', 'content', 'gender']
        widgets = {
            'email': forms.EmailInput(),
            'content': forms.TextInput(),
        }


class SearchForm(forms.Form):
    search_field = forms.CharField(max_length=10)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['search_field'].widget.attrs.update(
            {'class': 'form-control input-mf',
             'placeholder': 'جستجو برای ...',
             'aria-label': 'Search for...',
             'label': '',
             }
        )

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models.functions import Greatest
from django.views.generic import CreateView

from blog.models import *
from .forms import ContactUsForm, CommentForm, SearchForm


# def handleIndexPage(request):
#     if request.method == 'POST':
#         contact_form = ContactUsForm(request.POST)
#         if contact_form.is_valid():
#             contact_form.save()
#             return redirect('IndexView')
#
#     contact_form = ContactUsForm()
#
#     context = {
#         'about_Me': get_about_me(),
#         'my_skills': get_my_skills(),
#         'my_services': get_my_services(),
#         'my_reputations': get_my_reputations(),
#         'my_projects': get_my_projects(),
#         'my_testimonials': get_my_testimonials(),
#         'all_articles': get_all_articles(),
#         'contact_form': contact_form,
#     }
#
#     return render(request, 'blog/index.html', context)


class IndexPageView(CreateView):
    form_class = ContactUsForm
    template_name = 'blog/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexPageView, self).get_context_data(**kwargs)
        context.update({
            'about_Me': get_about_me(),
            'my_skills': get_my_skills(),
            'my_services': get_my_services(),
            'my_reputations': get_my_reputations(),
            'my_projects': get_my_projects(),
            'my_testimonials': get_my_testimonials(),
            'all_articles': get_all_articles()
        })
        return context


def blogSingleView(request, pk):
    latest_articles = get_all_articles()[:5]
    specific_article = get_object_or_404(Article, pk=pk)
    specific_comment = get_specific_comments(specific_article)

    search_response = get_all_articles()
    if request.method == 'GET':
        if 'search_field' in request.GET:
            search_form = SearchForm(request.GET)
            if search_form.is_valid():
                valid_search_field = search_form.cleaned_data['search_field']
                search_response = search_response.annotate(similarity=Greatest(
                    TrigramSimilarity('title', valid_search_field),
                    TrigramSimilarity('content', valid_search_field),
                    TrigramSimilarity('short_description', valid_search_field),
                )
                ).filter(similarity__gt=0.3).order_by('-similarity')
                try:
                    specific_article = search_response[0]
                except:
                    pass
                # print(specific_article.pk)
                return redirect('BlogSingleView', pk=specific_article.pk)
    search_form = SearchForm()

    # print(request.POST)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            name = comment_form.cleaned_data['name']
            email = comment_form.cleaned_data['email']
            content = comment_form.cleaned_data['content']
            gender = comment_form.cleaned_data['gender']
            comment = CommentUs.objects.create(
                name=name, email=email, content=content, article=specific_article, gender=gender)
            comment.save()
            return redirect('BlogSingleView', pk=pk)
    comment_form = CommentForm()

    context = {
        'specific_article': specific_article,
        'comment_form': comment_form,
        'specific_comment': specific_comment,
        'all_articles': latest_articles,
        'search_form': search_form,
    }

    return render(request, 'blog/blog-single.html', context)


def handle_archive_month(request, month):
    search_response = get_specific_articles(month)

    if 'search_field' in request.GET:
        search_form = SearchForm(request.GET)
        if search_form.is_valid():
            valid_search_field = search_form.cleaned_data['search_field']
            # search_response = search_response.filter(
            #     Q(title__icontains=valid_search_field) |
            #     Q(content__in=valid_search_field) |
            #     Q(short_description__in=valid_search_field)
            # )
            search_response = search_response.annotate(similarity=Greatest(
                TrigramSimilarity('title', valid_search_field),
                TrigramSimilarity('content', valid_search_field),
                TrigramSimilarity('short_description', valid_search_field),
            )
            ).filter(similarity__gt=0.3).order_by('-similarity')
    search_form = SearchForm()

    # print(search_response)
    context = {
        'search_response': search_response,
        'search_form': search_form,
    }
    return render(request, 'blog/archive.html', context)

blog/templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blog{% endblock title %}

<!--/ Nav Star /-->
{% block nav_1 %}
    <a class="navbar-brand js-scroll" href="{% url 'BlogSingleView' specific_article.pk %}">DevFolio</a>
{% endblock nav_1 %}

{% block nav_2 %}
    <div class="navbar-collapse collapse justify-content-end" id="navbarDefault">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link js-scroll active" href="{% url 'IndexView' %}">خانه</a>
            </li>
        </ul>
    </div>
{% endblock nav_2 %}>
<!--/ Nav End /-->

<!--/ Intro Skew Star /-->
{% block Skew %}
    <div class="intro intro-single route bg-image"
         style="background-image: url({% static 'blog/img/overlay-bg.jpg' %})">
        <div class="overlay-mf"></div>
        <div class="intro-content display-table">
            <div class="table-cell">
                <div class="container">
                    <h2 class="intro-title mb-4">وبلاگ</h2>
                    <ol class="breadcrumb d-flex justify-content-center">
                        <li class="breadcrumb-item">
                            <a href="{% url 'BlogSingleView' specific_article.pk %}">وبلاگ</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="{% url 'IndexView' %}">خانه</a>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock Skew %}
<!--/ Intro Skew End /-->

<!--/ Section Blog Star /-->
{% block Blog %}
    <section class="blog-wrapper sect-pt4" id="blog">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="post-box" style="background-color: #070606">
                        <div class="post-thumb">
                            <img style="width: 1200px;height: auto" src="{{ specific_article.cover.url }}"
                                 class="img-fluid" alt=""/>
                        </div>
                        <div class="post-meta">
                            <h1 class="article-title" style="color: white">
                                {{ specific_article.title }}
                            </h1>
                            <ul>
                                <li>
                                    <span class="ion-ios-person"></span>
                                    <a href="{% url 'IndexView' %}"
                                       style="color: white">{{ specific_article.author.user.first_name }} {{ specific_article.author.user.last_name }}</a>
                                </li>
                                <li>
                                    <span class="ion-pricetag"></span>
                                    <a href="#">{{ specific_article.category.title }}</a>
                                </li>
                                <li>
                                    <span class="ion-chatbox"></span>
                                    <a href="#comment">{{ specific_article.commentus_set.count }}</a>
                                </li>
                            </ul>
                        </div>
                        <div class="article-content" style="color: white">
                            <p>{{ specific_article.content|safe }}</p>
                            <blockquote class="blockquote">
                                <p class="mb-0">
                                    {{ specific_article.short_description|safe }}
                                </p>
                            </blockquote>
                        </div>
                    </div>
                    <div id="comment" class="box-comments" style="background-color: #070606">
                        <div class="title-box-2">
                            <h4 class="title-comments title-left" style="color: white">نظرات
                                ({{ specific_article.commentus_set.count }})</h4>
                        </div>
                        <ul class="list-comments">
                            {% for comment in specific_comment %}
                                <li>
                                    <div class="comment-avatar">
                                        {% if comment.gender == 'male' %}
                                            <img src="{% static 'blog/img/testimonial-2.jpg' %}" alt=""/>
                                        {% endif %}
                                        {% if comment.gender == 'female' %}
                                            <img src="{% static 'blog/img/testimonial-4.jpg' %}" alt=""/>
                                        {% endif %}
                                    </div>
                                    <div class="comment-details" style="color: white">
                                        <h4 class="comment-author" style="color: white">{{ comment.name }}</h4>
                                        <span style="color: white">{{ comment.created_at|date:'F , d, Y' }}</span>
                                        <p style="color: white">{{ comment.content|safe }}</p>
                                        <a href="#">پاسخ</a>
                                    </div>
                                </li>
                            {% empty %}
                                <h4>نظری وجود ندارد.<br>اولین نفری باشید که نظر می دهید.</h4>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="form-comments" style="background-color: #070606">
                        <div class="title-box-2">
                            <h3 class="title-left" style="color: white">
                                گذاشتن پاسخ
                            </h3>
                        </div>
                        <!--/ form for create comment /-->
                        <form class="form-mf" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <div class="form-group">
                                        {{ comment_form.name }}
                                    </div>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <div class="form-group">
                                        {{ comment_form.email }}
                                    </div>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <div class="form-group">
                                        {{ comment_form.media }}
                                        {{ comment_form.content|safe }}
                                    </div>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <div class="form-group">
                                        {{ comment_form.gender }}
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button type="submit" class="button button-a button-big button-rouded"
                                            style="color: white">
                                        ارسال پیام
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="widget-sidebar sidebar-search" style="background-color: #070606">
                        <h5 class="sidebar-title" style="color: white">جستجو</h5>
                        <div class="sidebar-content">
                            <form action="" method="get">
                                <div class="input-group">
                                    {{ search_form.search_field }}
                                    <span class="input-group-btn">
                                        <button class="btn btn-secondary btn-search" type="submit">
                                            <span class="ion-android-search"></span>
                                        </button>
                                    </span>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="widget-sidebar" style="background-color: #070606">
                        <h5 class="sidebar-title" style="color: white">پست های اخیر</h5>
                        <div class="sidebar-content">
                            <ul class="list-sidebar">
                                {% for post in all_articles %}
                                    <li>
                                        <a href="{% url 'BlogSingleView' post.pk %}"
                                           style="color: white">{{ post.title }}</a>
                                    </li>
                                {% endfor all_articles %}
                            </ul>
                        </div>
                    </div>
                    <div class="widget-sidebar" style="background-color: #070606">
                        <h5 class="sidebar-title" style="color: white">آرشیو</h5>
                        <div class="sidebar-content">
                            <ul class="list-sidebar">
                                <li>
                                    <a href="{% url 'ArchiveMonth' 1 %}" style="color: white">2020 January</a>
                                </li>
                                <li>
                                    <a href="{% url 'ArchiveMonth' 2 %}" style="color: white">2020 February</a>
                                </li>
                                <li>
                                    <a href="{% url 'ArchiveMonth' 3 %}" style="color: white">2020 March</a>
                                </li>
                                <li>
                                    <a href="{% url 'ArchiveMonth' 4 %}" style="color: white">2020 April</a>
                                </li>
                                <li>
                                    <a href="{% url 'ArchiveMonth' 5 %}" style="color: white">2020 May</a>
                                </li>
                                <li>
                                    <a href="{% url 'ArchiveMonth' 6 %}" style="color: white">2020 June</a>
                                </li>
                                <li>
                                    <a href="{% url 'ArchiveMonth' 7 %}" style="color: white">2020 July</a>
                                </li>
                                <li>
                                    <a href="{% url 'ArchiveMonth' 8 %}" style="color: white">2020 August</a>
                                </li>
                                <li>
                                    <a href="{% url 'ArchiveMonth' 9 %}" style="color: white">2020 September</a>
                                </li>
                                <li>
                                    <a href="{% url 'ArchiveMonth' 10 %}" style="color: white">2020 October</a>
                                </li>
                                <li>
                                    <a href="{% url 'ArchiveMonth' 11 %}" style="color: white">2020 November</a>
                                </li>
                                <li>
                                    <a href="{% url 'ArchiveMonth' 12 %}" style="color: white">2020 December</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="widget-sidebar widget-tags" style="background-color: #070606">
                        <h5 class="sidebar-title" style="color: white">تگ ها</h5>
                        <div class="sidebar-content">
                            <ul>
                                <li>
                                    <a href="#">وب</a>
                                </li>
                                <li>
                                    <a href="#">طراحی</a>
                                </li>
                                <li>
                                    <a href="#">سفر</a>
                                </li>
                                <li>
                                    <a href="#">فتوشاپ</a>
                                </li>
                                <li>
                                    <a href="#">طراحی سایت</a>
                                </li>
                                <li>
                                    <a href="#">جاوا اسکریپت</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock Blog %}
<!--/ Section Blog End /-->